# Generated by Django 3.1.1 on 2020-09-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=50)),
                ('average', models.CharField(max_length=4)),
                ('num_average', models.CharField(max_length=4)),
                ('num_credit', models.IntegerField(max_length=2)),
            ],
        ),
    ]
