# Generated by Django 3.1.1 on 2020-09-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='num_credit',
            field=models.IntegerField(),
        ),
    ]
